# Generated by Django 3.2.5 on 2021-07-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0004_category_expense_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='cash',
            field=models.IntegerField(default=0),
        ),
    ]
